version: "3.9"

services:
  otmonstermaker:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: on-failure
    volumes:
      - .:/otmonstermaker
    expose:
      - "3000"
    ports:
      - "3000:3000"
